In [1]:
#import libraries
from google.colab import files
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [3]:
#Read the dataset from drive
df = pd.read_csv('/content/drive/MyDrive/Neural/Churn_Modelling.csv')
print(df)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# Finding Missing Values
print(df.isnull().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
#Handling Missing values
df.fillna(df.select_dtypes(include='number').mean().round(1), inplace=True)
print(df.isnull().sum())

y = df.iloc[:, -1].values
print(y)

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
[1 0 1 ... 1 1 0]

In [7]:
#Check for Duplicates
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [10]:
df['EstimatedSalary'].describe()
scaler = StandardScaler()
inc_cols = ['CreditScore', 'Tenure', 'Balance', 'EstimatedSalary']
scaled_values = scaler.fit_transform(df[inc_cols])
df[inc_cols] = pd.DataFrame(scaled_values, columns = inc_cols, index = df.index)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,-0.326221,France,Female,42,-1.041760,-1.225848,1,1,1,0.021886,1
1,2,15647311,Hill,-0.440036,Spain,Female,41,-1.387538,0.117350,1,0,1,0.216534,0
2,3,15619304,Onio,-1.536794,France,Female,42,1.032908,1.333053,3,1,0,0.240687,1
3,4,15701354,Boni,0.501521,France,Female,39,-1.387538,-1.225848,2,0,0,-0.108918,0
4,5,15737888,Mitchell,2.063884,Spain,Female,43,-1.041760,0.785728,1,1,1,-0.365276,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,1.246488,France,Male,39,-0.004426,-1.225848,2,1,0,-0.066419,0
9996,9997,15569892,Johnstone,-1.391939,France,Male,35,1.724464,-0.306379,1,1,1,0.027988,0
9997,9998,15584532,Liu,0.604988,France,Female,36,0.687130,-1.225848,1,0,1,-1.008643,1
9998,9999,15682355,Sabbatini,1.256835,Germany,Male,42,-0.695982,-0.022608,2,1,0,-0.125231,1
9999,10000,15628319,Walker,1.463771,France,Female,28,-0.350204,0.859965,1,1,0,-1.076370,0

In [11]:

x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [12]:
#split the dataset into input and output
print("X Values")
x

print("Y Values")
y

X Values
Y Values

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [13]:
#splitting the data for training & Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [14]:
#Print the training data and testing data
print("X Training data")
x_train

print("X Testing data")
x_test

X Training data
X Testing data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
6252,6253,15687492,Anderson,-0.564197,Germany,Male,32,-0.695982,0.324119,2,0,0,-1.013811
4684,4685,15736963,Herring,-0.284834,France,Male,43,-1.387538,-1.225848,2,1,1,0.804921
1731,1732,15721730,Amechi,-0.512463,Spain,Female,44,-0.350204,-1.225848,2,1,0,-0.722147
4742,4743,15762134,Liang,-1.495407,Germany,Male,59,1.032908,0.683816,2,1,1,1.227481
4521,4522,15648898,Chuang,-0.936681,Spain,Female,27,0.687130,0.777477,1,1,1,0.253524
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,6413,15598982,Klein,-0.502117,Germany,Female,53,-0.004426,0.349118,1,0,1,-0.957298
8285,8286,15572631,Ndubuisi,-0.429689,France,Male,25,1.724464,-1.225848,1,0,1,0.170498
7853,7854,15746674,Miller,0.822271,France,Female,47,0.687130,-1.225848,1,1,0,-1.160142
1095,1096,15689081,Wu,0.429093,France,Male,29,-0.350204,-1.225848,1,1,0,-0.405759
6929,6930,15651627,White,-0.233100,Germany,Male,39,-1.387538,0.622738,1,1,1,0.131879

In [16]:
print(len(x_train))

8000

In [17]:
print(len(x_test))

2000